USE [master]
GO

/****** Object:  Database [PERSONAL]    Script Date: 04/09/2020 11:32:50 p. m. ******/
CREATE DATABASE [PERSONAL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PERSONAL', FILENAME = N'__PATH\PERSONAL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PERSONAL_log', FILENAME = N'__PATH\PERSONAL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PERSONAL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PERSONAL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PERSONAL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PERSONAL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PERSONAL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PERSONAL] SET ARITHABORT OFF 
GO

ALTER DATABASE [PERSONAL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PERSONAL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PERSONAL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PERSONAL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PERSONAL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PERSONAL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PERSONAL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PERSONAL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PERSONAL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PERSONAL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PERSONAL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PERSONAL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PERSONAL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PERSONAL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PERSONAL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PERSONAL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PERSONAL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PERSONAL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PERSONAL] SET  MULTI_USER 
GO

ALTER DATABASE [PERSONAL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PERSONAL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PERSONAL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PERSONAL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PERSONAL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PERSONAL] SET QUERY_STORE = OFF
GO

USE [PERSONAL]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [PERSONAL] SET  READ_WRITE 
GO


