USE [PERSONAL]
GO

/****** Object:  Table [dbo].[DEPARTAMENTO]    Script Date: 04/09/2020 11:28:40 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEPARTAMENTO](
	[Clave_Depto] [int] NOT NULL,
	[Nombre] [varchar](30) NOT NULL,
	[Presupuesto] [int] NULL,
 CONSTRAINT [PK_DEPARTAMENTO] PRIMARY KEY CLUSTERED 
(
	[Clave_Depto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


